---
title: "Lab 1"
author: "Saul Grimaldo and Melwin Poovakottu"
date: "1/18/2017"
output: pdf_document
---

```{r}
library(ggplot2)
setwd("../data/")
load("ceo_w203.RData")
```

You can also embed plots, for example:

```{r, echo=FALSE}
# We don't know how the option on education was presented. Perhaps it was set up so that a person can click on multiple educational levels in a single question, and some people who clicked on grad school but not college were unaware of this. Under this analysis, we'll accept this as a true assumption
CEO$education = as.factor(with(CEO, ifelse(grad == 1, 2, ifelse(college == 1, 1, 0))))


summary(CEO$education)


ggplot(CEO, aes(x = log(salary), y = log(profits), color = as.factor(grad))) +geom_point() + stat_smooth(method = "lm")

ggplot(CEO, aes(x = comten, y = log(profits), color = as.factor(grad))) +geom_point() + stat_smooth(method = "lm")

ggplot(CEO, aes(x = ceoten, y = log(profits), color = as.factor(grad))) +geom_point() + stat_smooth(method = "lm")

CEO$NotCeoTen = CEO$comten - CEO$ceoten 


ggplot(CEO, aes(x = NotCeoTen, y = log(profits), color = as.factor(grad))) + geom_point() + stat_smooth(method = "lm")

boxplot(CEO$profits ~ CEO$NotCeoTen, range = 10 )

### mention negative notceoten






ggplot(CEO, aes(x = age, y = mktval, color = as.factor(grad))) +geom_point() + stat_smooth(method = "lm")




sub = CEO$salary<=3000 & CEO$profits<=1000 & CEO$profits>00
subCeo=CEO[sub,]
plot( subCeo$salary,log(subCeo$profits))
abline(lm(log(subCeo$profits)~subCeo$salary),col="red")



```
age is dropping dramatically after 65. Not too correlated
